"""The hub's shipped copy must equal the hub's source.

`configMapGenerator` refuses files outside its kustomization root, so
`deploy/oke/zippie-hub/hub-app/` holds byte-identical copies of the real hub
sources. Two copies of a file in one repo drift; that is not a risk, it is a
certainty with a date on it. This is the guard that puts the date at "the next
CI run" instead of "whenever somebody notices the hub is wrong".

The precedent is `test_manifest_copy_in_sync.py`, which does the same job for
zippie-home's `zippie-pkg/`. This module deliberately mirrors its shape rather
than inventing a second convention.

WHAT THIS EXISTS TO PREVENT, concretely. Until 2026-08-08 the ConfigMap the hub
mounts was created BY HAND (`managed-by: (none)`) and generated by nothing, so
editing hub.py on main changed git and left the running pod untouched -
deployed-looking and inert (#37, and quadseven/zippie#15 was held open for it).
Generating the ConfigMap fixes that; this test is what stops the fix rotting
into the same failure through a stale copy instead of an absent one.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[3]
SHIPPED = REPO / "deploy" / "oke" / "zippie-hub" / "hub-app"

# shipped filename -> its canonical source. Held EQUAL, not merely overlapping:
# a file in one side and not the other fails below, in both directions.
PAIRS = {
    "hub.py": REPO / "hub" / "hub.py",
    "hub.js": REPO / "hub" / "static" / "hub.js",
    "hub.css": REPO / "hub" / "static" / "hub.css",
    "index.html": REPO / "hub" / "static" / "index.html",
    "tokens.generated.css": REPO / "hub" / "static" / "tokens.generated.css",
}


def _sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


@pytest.mark.parametrize("name", sorted(PAIRS))
def test_shipped_copy_matches_its_source(name):
    src = PAIRS[name]
    dst = SHIPPED / name
    assert src.is_file(), f"source missing: {src.relative_to(REPO)}"
    assert dst.is_file(), (
        f"{name} is listed as shipped but is not in {SHIPPED.relative_to(REPO)} - "
        f"the hub would mount a ConfigMap without it"
    )
    assert _sha(src) == _sha(dst), (
        f"{name} has drifted.\n"
        f"  source:  {src.relative_to(REPO)}\n"
        f"  shipped: {dst.relative_to(REPO)}\n"
        f"Copy the source over the shipped file. The source is authoritative - "
        f"the shipped copy exists only because configMapGenerator cannot reach "
        f"outside its root."
    )


def test_no_shipped_file_is_unlisted():
    """A file in the directory but not in PAIRS is shipped and unchecked.

    That is the exact hole zippie-home had: agent.py and policy.py sat in
    zippie-pkg/ in neither the generator list nor the drift guard, unshipped and
    unchecked, one of them already two changes stale (quadseven/infra#2277).
    """
    on_disk = {p.name for p in SHIPPED.iterdir() if p.is_file()}
    assert on_disk == set(PAIRS), (
        f"directory and guard disagree.\n"
        f"  only on disk: {sorted(on_disk - set(PAIRS))}\n"
        f"  only in guard: {sorted(set(PAIRS) - on_disk)}\n"
        f"Adding a hub asset means editing BOTH this list AND the "
        f"configMapGenerator in deploy/oke/zippie-hub/kustomization.yaml."
    )


def test_generator_list_matches_the_directory():
    """The kustomization must generate exactly these files.

    Three places have to agree - the directory, this guard, and the generator.
    Two-way agreement lets the third rot silently, which is how a file gets
    copied and reviewed and still never reaches the pod.
    """
    kustomization = (REPO / "deploy" / "oke" / "zippie-hub" / "kustomization.yaml").read_text()
    listed = {
        line.strip().removeprefix("- hub-app/")
        for line in kustomization.splitlines()
        if line.strip().startswith("- hub-app/")
    }
    assert listed == set(PAIRS), (
        f"kustomization.yaml and this guard disagree.\n"
        f"  only in kustomization: {sorted(listed - set(PAIRS))}\n"
        f"  only in guard: {sorted(set(PAIRS) - listed)}"
    )


def test_tokens_css_is_the_generated_one_not_a_hand_edit():
    """tokens.generated.css is produced by design/generate.py.

    The live ConfigMap's copy on 2026-08-08 was 36 bytes LARGER than the repo's,
    differing only in a comment header that still named the pre-split
    `production/zippie/design/` paths - i.e. a stale artifact hand-applied
    before the repo split, not a newer version. Shipping a hand-edited token
    file would silently diverge the hub from every other surface the design
    tokens feed.
    """
    text = (SHIPPED / "tokens.generated.css").read_text()
    assert "DO NOT EDIT" in text, "the generated banner is missing - was this hand-written?"
    assert "production/zippie/design" not in text, (
        "this is the pre-split copy; regenerate with design/generate.py"
    )
